"""Corrected CsvSummaryMasterDaily model

Revision ID: 4f976a3bff04
Revises: 2eea24f1be33
Create Date: 2025-11-12 04:31:05.711320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f976a3bff04'
down_revision: Union[str, Sequence[str], None] = '2eea24f1be33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
