"""Initial schema creation

Revision ID: 5494ba9c7927
Revises: 
Create Date: 2025-11-12 04:04:51.890052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import SQLiteARRAY


# revision identifiers, used by Alembic.
revision: str = '5494ba9c7927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accumulated_anomaly_criteria',
    sa.Column('accumulated_criteria_id', sa.Integer(), nullable=False),
    sa.Column('criteria_code', sa.String(), nullable=False),
    sa.Column('criteria_name', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('time_window_hours', sa.Integer(), nullable=True),
    sa.Column('group_by_field', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('accumulated_criteria_id'),
    sa.UniqueConstraint('criteria_code')
    )
    op.create_index(op.f('ix_accumulated_anomaly_criteria_accumulated_criteria_id'), 'accumulated_anomaly_criteria', ['accumulated_criteria_id'], unique=False)
    op.create_table('anomaly_template_master',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_anomaly_template_master_template_id'), 'anomaly_template_master', ['template_id'], unique=False)
    op.create_table('csv_summary_master_daily',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_datetime', sa.DateTime(), nullable=False),
    sa.Column('import_duration', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('total_records_inserted', sa.Integer(), nullable=True),
    sa.Column('total_records_read', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('total_penjualan', sa.String(), nullable=True),
    sa.Column('total_operator', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('produk_jbt', sa.String(), nullable=True),
    sa.Column('produk_jbkt', sa.String(), nullable=True),
    sa.Column('total_volume_liter', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_penjualan_rupiah', sa.String(), nullable=True),
    sa.Column('total_mode_transaksi', sa.String(), nullable=True),
    sa.Column('total_plat_nomor', sa.String(), nullable=True),
    sa.Column('total_nik', sa.String(), nullable=True),
    sa.Column('sektor_non_kendaraan', sa.String(), nullable=True),
    sa.Column('jumlah_roda_kendaraan_4', sa.String(), nullable=True),
    sa.Column('total_jumlah_roda_kendaraan_6', sa.String(), nullable=True),
    sa.Column('total_kuota', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('total_warna_plat_kuning', sa.String(), nullable=True),
    sa.Column('total_warna_plat_hitam', sa.String(), nullable=True),
    sa.Column('total_warna_plat_merah', sa.String(), nullable=True),
    sa.Column('total_warna_plat_putih', sa.String(), nullable=True),
    sa.Column('total_mor', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('total_provinsi', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('total_kota_kabupaten', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('total_no_spbu', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('numeric_totals', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_csv_summary_master_daily_summary_id'), 'csv_summary_master_daily', ['summary_id'], unique=False)
    op.create_table('special_anomaly_criteria',
    sa.Column('special_criteria_id', sa.Integer(), nullable=False),
    sa.Column('criteria_code', sa.String(), nullable=False),
    sa.Column('criteria_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('violation_rule', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('special_criteria_id'),
    sa.UniqueConstraint('criteria_code')
    )
    op.create_index(op.f('ix_special_anomaly_criteria_special_criteria_id'), 'special_anomaly_criteria', ['special_criteria_id'], unique=False)
    op.create_table('tabel_mor',
    sa.Column('mor_id', sa.Integer(), nullable=False),
    sa.Column('mor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mor_id')
    )
    op.create_index(op.f('ix_tabel_mor_mor_id'), 'tabel_mor', ['mor_id'], unique=False)
    op.create_table('transaction_anomaly_criteria',
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('min_volume_liter', sa.Integer(), nullable=False),
    sa.Column('plate_color', SQLiteARRAY(), nullable=True),
    sa.Column('consumer_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('criteria_id')
    )
    op.create_index(op.f('ix_transaction_anomaly_criteria_criteria_id'), 'transaction_anomaly_criteria', ['criteria_id'], unique=False)
    op.create_table('video_ai_parameters',
    sa.Column('param_id', sa.Integer(), nullable=False),
    sa.Column('parameter_key', sa.String(), nullable=False),
    sa.Column('parameter_value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('user_modifiable', sa.Boolean(), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('param_id'),
    sa.UniqueConstraint('parameter_key')
    )
    op.create_index(op.f('ix_video_ai_parameters_param_id'), 'video_ai_parameters', ['param_id'], unique=False)
    op.create_table('anomaly_executions',
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_by', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rules_applied', SQLiteARRAY(), nullable=False),
    sa.Column('rules_config', sa.JSON(), nullable=True),
    sa.Column('total_batches_processed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['anomaly_template_master.template_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('csv_import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id_asersi', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('jam', sa.String(), nullable=False),
    sa.Column('mor', sa.String(), nullable=True),
    sa.Column('provinsi', sa.String(), nullable=True),
    sa.Column('kota_kabupaten', sa.String(), nullable=True),
    sa.Column('no_spbu', sa.String(), nullable=True),
    sa.Column('no_nozzle', sa.String(), nullable=True),
    sa.Column('no_dispenser', sa.String(), nullable=True),
    sa.Column('produk', sa.String(), nullable=True),
    sa.Column('volume_liter', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('penjualan_rupiah', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('mode_transaksi', sa.String(), nullable=True),
    sa.Column('plat_nomor', sa.String(), nullable=True),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('sektor_non_kendaraan', sa.String(), nullable=True),
    sa.Column('jumlah_roda_kendaraan', sa.String(), nullable=True),
    sa.Column('kuota', sa.String(), nullable=True),
    sa.Column('warna_plat', sa.String(), nullable=True),
    sa.Column('daily_summary_id', sa.BigInteger(), nullable=True),
    sa.Column('import_attempt_count', sa.Integer(), nullable=True),
    sa.Column('batch_original_duplicate_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_summary_id'], ['csv_summary_master_daily.summary_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id_asersi')
    )
    op.create_index(op.f('ix_csv_import_log_id'), 'csv_import_log', ['id'], unique=False)
    op.create_table('template_criteria_accumulated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('accumulated_criteria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accumulated_criteria_id'], ['accumulated_anomaly_criteria.accumulated_criteria_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['anomaly_template_master.template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_criteria_special',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('special_criteria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['special_criteria_id'], ['special_anomaly_criteria.special_criteria_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['anomaly_template_master.template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_criteria_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('param_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['param_id'], ['video_ai_parameters.param_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['anomaly_template_master.template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_criteria_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('criteria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criteria_id'], ['transaction_anomaly_criteria.criteria_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['anomaly_template_master.template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_execution_batches',
    sa.Column('detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('batch_status', sa.String(length=50), nullable=True),
    sa.Column('anomalies_found', sa.Integer(), nullable=True),
    sa.Column('p1_anomaly_value', sa.String(), nullable=True),
    sa.Column('p2_anomaly_value', sa.String(), nullable=True),
    sa.Column('p3_anomaly_value', sa.String(), nullable=True),
    sa.Column('p4_anomaly_value', sa.String(), nullable=True),
    sa.Column('p5_anomaly_value', sa.String(), nullable=True),
    sa.Column('p6_anomaly_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['anomaly_executions.execution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['csv_summary_master_daily.summary_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('anomaly_results',
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_id_asersi', sa.String(length=50), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.Column('anomaly_flags', SQLiteARRAY(), nullable=True),
    sa.Column('violation_details', sa.JSON(), nullable=True),
    sa.Column('anomaly_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['anomaly_executions.execution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['anomaly_template_master.template_id'], ),
    sa.PrimaryKeyConstraint('transaction_id_asersi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_results')
    op.drop_table('anomaly_execution_batches')
    op.drop_table('template_criteria_volume')
    op.drop_table('template_criteria_video')
    op.drop_table('template_criteria_special')
    op.drop_table('template_criteria_accumulated')
    op.drop_index(op.f('ix_csv_import_log_id'), table_name='csv_import_log')
    op.drop_table('csv_import_log')
    op.drop_table('anomaly_executions')
    op.drop_index(op.f('ix_video_ai_parameters_param_id'), table_name='video_ai_parameters')
    op.drop_table('video_ai_parameters')
    op.drop_index(op.f('ix_transaction_anomaly_criteria_criteria_id'), table_name='transaction_anomaly_criteria')
    op.drop_table('transaction_anomaly_criteria')
    op.drop_index(op.f('ix_tabel_mor_mor_id'), table_name='tabel_mor')
    op.drop_table('tabel_mor')
    op.drop_index(op.f('ix_special_anomaly_criteria_special_criteria_id'), table_name='special_anomaly_criteria')
    op.drop_table('special_anomaly_criteria')
    op.drop_index(op.f('ix_csv_summary_master_daily_summary_id'), table_name='csv_summary_master_daily')
    op.drop_table('csv_summary_master_daily')
    op.drop_index(op.f('ix_anomaly_template_master_template_id'), table_name='anomaly_template_master')
    op.drop_table('anomaly_template_master')
    op.drop_index(op.f('ix_accumulated_anomaly_criteria_accumulated_criteria_id'), table_name='accumulated_anomaly_criteria')
    op.drop_table('accumulated_anomaly_criteria')
    # ### end Alembic commands ###
