"""Rename jumlah_roda_kendaraan columns in csv_summary_master_daily

Revision ID: 6f370e0ade66
Revises: 4f976a3bff04
Create Date: 2025-11-12 05:26:23.007161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f370e0ade66'
down_revision: Union[str, Sequence[str], None] = '4f976a3bff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_summary_master_daily', 'jumlah_roda_kendaraan_4', 
                    new_column_name='total_jumlah_roda_kendaraan_4', 
                    existing_type=sa.VARCHAR(50), 
                    type_=sa.VARCHAR(50), 
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csv_summary_master_daily', 'total_jumlah_roda_kendaraan_4', 
                    new_column_name='jumlah_roda_kendaraan_4', 
                    existing_type=sa.VARCHAR(50), 
                    type_=sa.VARCHAR(50), 
                    existing_nullable=True)
    # ### end Alembic commands ###
