"""Add file_type to CsvSummaryMasterDaily

Revision ID: fe24393a021d
Revises: 5494ba9c7927
Create Date: 2025-11-12 04:27:56.007223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe24393a021d'
down_revision: Union[str, Sequence[str], None] = '5494ba9c7927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_summary_master_daily', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_summary_master_daily', 'file_type')
    # ### end Alembic commands ###
